export default {
    TODO_CREATE: "TODO_CREATE",
    TODO_DELETE: "TODO_DESTROY",
    TODO_UPDATE: "TODO_UPDATE",
    TODO_TOGGLE_COMPLETE: "TODO_TOGGLE_COMPLETE",
    TODO_TOGGLE_COMPLETE_ALL: "TODO_TOGGLE_COMPLETE_ALL",
    TODO_TOGGLE_UNCOMPLETE: "TODO_TOGGLE_UNCOMPLETE"
}
